name: team_call
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.14.0+5
  iamport_flutter: ^0.9.15

  top_snackbar_flutter: ^1.0.0
  intl: ^0.16.1
  url_launcher: ^5.7.10
  flutter_phone_direct_caller: ^2.0.0
  permission_handler: ^5.0.1
  uuid: 3.0.4
  background_fetch: ^0.7.3
  fluttertoast: ^7.1.8
  #shared_preferences: ^2.0.6
  #/13

  flutter_incoming_call:
    path: ./flutter_incoming_call

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo22.png
    - assets/logo33.png
    - assets/text2.png
    - assets/add.png
  fonts:
    - family: Kopup
      fonts:
        - asset: assets/fonts/KoPubDotumLight.ttf
          weight: 300
        - asset: assets/fonts/KoPubDotumMedium.ttf
        - asset: assets/fonts/KoPubDotumBold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
